{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  buildInputs = [
    pkgs.glibc
    pkgs.chromium
    pkgs.fonts-liberation
    pkgs.libappindicator-gtk3
    pkgs.alsaLib
    pkgs.atk
    pkgs.glib
    pkgs.gtk3
    pkgs.nss
    pkgs.libx11
    pkgs.libxcomposite
    pkgs.libxcursor
    pkgs.libxdamage
    pkgs.libxfixes
    pkgs.libxi
    pkgs.libxrandr
    pkgs.libxss
    pkgs.libxtst
    pkgs.xdg-utils
  ];
}
